name: Update README Text

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          texts=("First message" "Second message" "Third message")
          selected_text=${texts[$(( RANDOM % 3 ))]}
          echo "Updating README with: $selected_text"
          
          # Replace the dynamic text placeholder
          sed -i "s/<!-- dynamic-text -->/${selected_text}/g" README.md

      - name: Set up Git for Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check for Changes
        run: |
          git diff --exit-code || git add README.md
          git diff --staged --exit-code || git commit -m "Update README text"

      - name: Push Changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
